{
    ["actionbar"] = {
        ["bar1"] = {
            ["backdropSpacing"] = 1,
            ["buttonSize"] = 28,
            ["buttonSpacing"] = 1,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["inheritGlobalFade"] = true,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOM",
            ["macroTextYOffset"] = 0,
            ["macrotext"] = true,
        },
        ["bar10"] = {
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
        },
        ["bar2"] = {
            ["buttonSize"] = 28,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOM",
            ["macrotext"] = true,
            ["mouseover"] = true,
        },
        ["bar3"] = {
            ["backdropSpacing"] = 4,
            ["buttonSize"] = 28,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOM",
            ["macroTextYOffset"] = 0,
            ["macrotext"] = true,
            ["mouseover"] = true,
        },
        ["bar4"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 28,
            ["buttonSpacing"] = 1,
            ["buttonsPerRow"] = 6,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = false,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOM",
            ["macroTextYOffset"] = 0,
            ["macrotext"] = true,
            ["mouseover"] = true,
        },
        ["bar5"] = {
            ["buttonSize"] = 28,
            ["buttonSpacing"] = 1,
            ["buttons"] = 12,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOM",
            ["macroTextYOffset"] = 0,
            ["macrotext"] = true,
            ["mouseover"] = true,
        },
        ["bar6"] = {
            ["buttonSize"] = 28,
            ["buttonSpacing"] = 1,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["enabled"] = true,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
            ["macroTextPosition"] = "BOTTOM",
            ["macroTextYOffset"] = 0,
            ["macrotext"] = true,
            ["mouseover"] = true,
        },
        ["bar7"] = {
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
        },
        ["bar8"] = {
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
        },
        ["bar9"] = {
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
            ["macroFont"] = "Mikko",
            ["macroFontOutline"] = "OUTLINE",
            ["macroFontSize"] = 12,
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["buttonSize"] = 28,
            ["buttonsPerRow"] = 10,
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 12,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["cooldown"] = {
            ["checkSeconds"] = true,
            ["fonts"] = {
                ["enable"] = true,
                ["font"] = "GothamNarrowUltra",
                ["fontSize"] = 14,
            },
            ["threshold"] = -1,
        },
        ["extraActionButton"] = {
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["font"] = "Mikko",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 12,
        ["globalFadeAlpha"] = 1,
        ["microbar"] = {
            ["enabled"] = true,
            ["mouseover"] = true,
        },
        ["stanceBar"] = {
            ["enabled"] = false,
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
        ["useDrawSwipeOnCharges"] = true,
        ["vehicleExitButton"] = {
            ["hotkeyFont"] = "Mikko",
            ["hotkeyFontOutline"] = "OUTLINE",
            ["hotkeyFontSize"] = 12,
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["countXOffset"] = -8,
            ["countYOffset"] = 24,
            ["horizontalSpacing"] = 3,
            ["timeFont"] = "Mikko",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 14,
            ["timeYOffset"] = 8,
        },
        ["cooldown"] = {
            ["checkSeconds"] = true,
            ["threshold"] = -1,
        },
        ["debuffs"] = {
            ["countFont"] = "Mikko",
            ["countFontOutline"] = "OUTLINE",
            ["countFontSize"] = 14,
            ["countXOffset"] = -8,
            ["countYOffset"] = 24,
            ["horizontalSpacing"] = 3,
            ["timeFont"] = "Mikko",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 14,
            ["timeYOffset"] = 8,
        },
    },
    ["bags"] = {
        ["bagSize"] = 33,
        ["cooldown"] = {
            ["fonts"] = {
                ["enable"] = true,
                ["font"] = "GothamNarrowUltra",
            },
        },
        ["countFont"] = "Mikko",
        ["countFontOutline"] = "OUTLINE",
        ["countFontSize"] = 12,
        ["itemInfoFont"] = "Mikko",
        ["itemInfoFontOutline"] = "OUTLINE",
        ["itemLevelFont"] = "Mikko",
        ["itemLevelFontOutline"] = "OUTLINE",
        ["itemLevelFontSize"] = 12,
        ["moneyFormat"] = "BLIZZARD",
        ["vendorGrays"] = {
            ["enable"] = true,
        },
    },
    ["chat"] = {
        ["chatHistory"] = false,
        ["editBoxPosition"] = "ABOVE_CHAT",
        ["emotionIcons"] = false,
        ["font"] = "Mikko",
        ["fontSize"] = 12,
        ["lfgIcons"] = false,
        ["panelBackdrop"] = "HIDEBOTH",
        ["panelHeight"] = 210,
        ["panelHeightRight"] = 266,
        ["panelWidth"] = 450,
        ["panelWidthRight"] = 533,
        ["separateSizes"] = true,
        ["tabFont"] = "Mikko",
        ["tabFontOutline"] = "OUTLINE",
        ["tabFontSize"] = 11,
    },
    ["convertPages"] = true,
    ["cooldown"] = {
        ["checkSeconds"] = true,
        ["fonts"] = {
            ["enable"] = true,
            ["font"] = "Mikko",
        },
        ["secondsColor"] = {
            ["b"] = 1,
        },
        ["threshold"] = -1,
    },
    ["databars"] = {
        ["azerite"] = {
            ["enable"] = false,
            ["font"] = "Mikko",
            ["fontOutline"] = "OUTLINE",
            ["fontSize"] = 16,
            ["height"] = 5,
            ["textFormat"] = "PERCENT",
            ["width"] = 340,
        },
        ["colors"] = {
            ["experience"] = {
                ["a"] = 1,
            },
        },
        ["experience"] = {
            ["font"] = "Mikko",
            ["fontOutline"] = "OUTLINE",
            ["height"] = 5,
            ["textFormat"] = "PERCENT",
            ["width"] = 340,
        },
        ["honor"] = {
            ["enable"] = false,
            ["font"] = "Mikko",
            ["fontOutline"] = "OUTLINE",
        },
        ["reputation"] = {
            ["font"] = "Mikko",
            ["fontOutline"] = "OUTLINE",
            ["fontSize"] = 16,
            ["height"] = 5,
            ["width"] = 340,
        },
        ["statusbar"] = "Melli",
        ["threat"] = {
            ["enable"] = false,
        },
    },
    ["datatexts"] = {
        ["font"] = "Mikko",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 14,
        ["panels"] = {
            ["BuiMiddleDTPanel"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                ["enable"] = false,
            },
            ["Darth_Panel_1"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                [4] = "",
                [5] = "",
                [6] = "",
                [7] = "",
                [8] = "",
                ["enable"] = false,
            },
            ["LeftChatDataPanel"] = {
                [2] = "System",
                ["enable"] = false,
            },
            ["LeftMiniPanel"] = "Time",
            ["Luckyone_ActionBars_DT"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                ["enable"] = false,
            },
            ["MER_RightChatTop"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                ["enable"] = false,
            },
            ["MikkoBottomLeftDTPanel"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                [4] = "",
                [5] = "",
                [6] = "",
                [7] = "",
                [8] = "",
                ["enable"] = false,
            },
            ["MinimapPanel"] = {
                [1] = "Time",
                [2] = "Time",
                ["backdrop"] = false,
                ["border"] = false,
                ["numPoints"] = 1,
                ["panelTransparency"] = true,
            },
            ["Player Name"] = {
                [1] = "",
                [2] = "",
                [3] = "",
                ["enable"] = false,
            },
            ["RightChatDataPanel"] = {
                ["enable"] = false,
            },
            ["RightMiniPanel"] = "ElvUI Config",
        },
    },
    ["general"] = {
        ["afk"] = false,
        ["altPowerBar"] = {
            ["font"] = "Mikko",
            ["fontSize"] = 14,
        },
        ["autoAcceptInvite"] = true,
        ["backdropfadecolor"] = {
            ["a"] = 0.80000001192093,
            ["b"] = 0.058823529411765,
            ["g"] = 0.058823529411765,
            ["r"] = 0.058823529411765,
        },
        ["bottomPanel"] = false,
        ["font"] = "Mikko",
        ["itemLevel"] = {
            ["itemLevelFont"] = "Mikko",
        },
        ["loginmessage"] = false,
        ["lootRoll"] = {
            ["nameFont"] = "Mikko",
        },
        ["minimap"] = {
            ["icons"] = {
                ["queueStatus"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                },
            },
            ["locationFont"] = "Mikko",
        },
        ["objectiveFrameHeight"] = 450,
        ["totems"] = {
            ["growthDirection"] = "HORIZONTAL",
            ["spacing"] = 1,
        },
        ["valuecolor"] = {
            ["b"] = 0.93333131074905,
            ["g"] = 0.53333216905594,
            ["r"] = 0.52941060066223,
        },
    },
    ["movers"] = {
        ["AlertFrameMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,49,-35",
        ["AltPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,84",
        ["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-457,-373",
        ["ArtifactBarMover"] = "TOP,ElvUIParent,TOP,0,-4",
        ["AzeriteBarMover"] = "TOP,ElvUIParent,TOP,0,-7",
        ["BNETMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-5,-205",
        ["BelowMinimapContainerMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-366,-346",
        ["BossButton"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-471,36",
        ["BossHeaderMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-390,393",
        ["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-193,-5",
        ["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,381",
        ["ComboBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,325",
        ["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-193,-148",
        ["DurabilityFrameMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-597,187",
        ["ElvAB_1"] = "BOTTOM,UIParent,BOTTOM,1,5",
        ["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,-262,3",
        ["ElvAB_3"] = "BOTTOM,UIParent,BOTTOM,-261,5",
        ["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,261,3",
        ["ElvAB_5"] = "BOTTOM,UIParent,BOTTOM,263,4",
        ["ElvAB_6"] = "BOTTOM,UIParent,BOTTOM,0,34",
        ["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,69,1014",
        ["ElvUF_BodyGuardMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,478,251",
        ["ElvUF_FocusCastbarMover"] = "TOP,ElvUIParent,TOP,0,-323",
        ["ElvUF_FocusMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,463,322",
        ["ElvUF_PartyMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,403,393",
        ["ElvUF_PetCastbarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,141,-4",
        ["ElvUF_PetMover"] = "BOTTOM,ElvUIParent,BOTTOM,-224,292",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,226",
        ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-284,322",
        ["ElvUF_Raid40Mover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,12,354",
        ["ElvUF_RaidMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,101,354",
        ["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,0,764",
        ["ElvUF_TankMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,1076",
        ["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,267,283",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,284,322",
        ["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-464,322",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-262,4",
        ["ExperienceBarMover"] = "TOP,ElvUIParent,TOP,0,-21",
        ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,4",
        ["LootFrameMover"] = "TOP,ElvUIParent,TOP,-192,-448",
        ["LossControlMover"] = "TOP,ElvUIParent,TOP,0,-491",
        ["MawBuffsBelowMinimapMover"] = "TOP,UIParent,TOP,0,-4",
        ["MicrobarMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,4",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-5,-5",
        ["ObjectiveFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-54,-200",
        ["PetAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,178",
        ["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,370",
        ["ReputationBarMover"] = "TOP,ElvUIParent,TOP,0,-35",
        ["RightChatMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,17",
        ["ShiftAB"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,768",
        ["TalkingHeadFrameMover"] = "BOTTOM,UIParent,BOTTOM,26,178",
        ["TargetPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,311,316",
        ["TooltipMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-273,288",
        ["TopCenterContainerMover"] = "TOP,ElvUIParent,TOP,0,-55",
        ["TotemBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,216",
        ["VehicleLeaveButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,212",
        ["VehicleSeatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,527,29",
        ["ZoneAbility"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-471,36",
    },
    ["nameplates"] = {
        ["colors"] = {
            ["castbarDesaturate"] = false,
            ["selection"] = {
                [0] = {
                    ["b"] = 0.30980392156863,
                    ["g"] = 0.29803921568628,
                },
                [2] = {
                    ["b"] = 0.43137254901961,
                    ["g"] = 0.93333333333333,
                },
                [3] = {
                    ["b"] = 0.25490196078431,
                    ["g"] = 0.74117647058823,
                    ["r"] = 0.32549019607843,
                },
            },
            ["threat"] = {
                ["badColor"] = {
                    ["b"] = 0.30980392156863,
                    ["g"] = 0.29803921568628,
                },
                ["goodColor"] = {
                    ["b"] = 0.23137254901961,
                    ["g"] = 0.87450980392157,
                    ["r"] = 0.38039215686275,
                },
                ["goodTransition"] = {
                    ["b"] = 0.43137254901961,
                    ["g"] = 0.93333333333333,
                },
            },
        },
        ["cooldown"] = {
            ["fonts"] = {
                ["enable"] = true,
                ["font"] = "Mikko",
                ["fontSize"] = 22,
            },
            ["threshold"] = -1,
        },
        ["filters"] = {
            ["Caster mobs"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["ElvUI_NonTarget"] = {
                ["triggers"] = {
                    ["enable"] = false,
                },
            },
            ["ElvUI_Target"] = {
                ["triggers"] = {
                    ["enable"] = false,
                },
            },
            ["Emissary of the Tides"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Enemy NPCs"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Mark of the Crane"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Shaman totems"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Spawn of G'huun"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Special mobs"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Thing"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
            ["Void-Touched Emissary"] = {
                ["triggers"] = {
                    ["enable"] = true,
                },
            },
        },
        ["lowHealthThreshold"] = 0.01,
        ["plateSize"] = {
            ["enemyHeight"] = 26,
        },
        ["smoothbars"] = true,
        ["statusbar"] = "Melli",
        ["units"] = {
            ["ENEMY_NPC"] = {
                ["buffs"] = {
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 14,
                    ["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,CastByNPC,PlayerBuffs,TurtleBuffs,CastByUnit",
                    ["size"] = 28,
                    ["yOffset"] = -6,
                },
                ["castbar"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["height"] = 20,
                    ["iconOffsetY"] = -1,
                    ["iconSize"] = 37,
                    ["sourceInterrupt"] = false,
                    ["textPosition"] = "ONBAR",
                    ["yOffset"] = -18,
                },
                ["debuffs"] = {
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 14,
                    ["font"] = "GothamNarrowUltra",
                    ["fontSize"] = 12,
                    ["priority"] = "Blacklist,Personal,CastByNPC",
                    ["size"] = 18,
                    ["yOffset"] = -4,
                },
                ["health"] = {
                    ["height"] = 14,
                    ["text"] = {
                        ["font"] = "Mikko",
                        ["fontSize"] = 14,
                        ["format"] = "[perhp]%",
                        ["position"] = "BOTTOMRIGHT",
                        ["yOffset"] = 14,
                    },
                },
                ["level"] = {
                    ["enable"] = false,
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["xOffset"] = 22,
                    ["yOffset"] = -15,
                },
                ["name"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["format"] = "[name:medium]",
                    ["yOffset"] = -6,
                },
            },
            ["ENEMY_PLAYER"] = {
                ["buffs"] = {
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 14,
                    ["enable"] = false,
                    ["maxDuration"] = 0,
                    ["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,CastByNPC,PlayerBuffs,TurtleBuffs,CastByUnit",
                    ["size"] = 28,
                    ["yOffset"] = -6,
                },
                ["castbar"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["height"] = 20,
                    ["iconOffsetY"] = -1,
                    ["iconSize"] = 37,
                    ["sourceInterrupt"] = false,
                    ["textPosition"] = "ONBAR",
                    ["yOffset"] = -18,
                },
                ["debuffs"] = {
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 14,
                    ["font"] = "GothamNarrowUltra",
                    ["fontSize"] = 12,
                    ["priority"] = "Blacklist,Personal,CastByNPC",
                    ["size"] = 22,
                    ["xOffset"] = -2,
                    ["yOffset"] = -4,
                },
                ["health"] = {
                    ["height"] = 14,
                    ["text"] = {
                        ["font"] = "Mikko",
                        ["fontSize"] = 14,
                        ["format"] = "[perhp]%",
                        ["position"] = "BOTTOMRIGHT",
                        ["yOffset"] = 16,
                    },
                },
                ["level"] = {
                    ["enable"] = false,
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["format"] = "[difficultycolor][level][shortclassification]",
                    ["xOffset"] = 22,
                    ["yOffset"] = -15,
                },
                ["name"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["format"] = "[name:medium]",
                    ["yOffset"] = -8,
                },
                ["title"] = {
                    ["format"] = "[npctitle]",
                },
            },
            ["FRIENDLY_NPC"] = {
                ["castbar"] = {
                    ["font"] = "Mikko",
                },
                ["questIcon"] = {
                    ["enable"] = false,
                },
            },
            ["FRIENDLY_PLAYER"] = {
                ["buffs"] = {
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 14,
                    ["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,PlayerBuffs,TurtleBuffs,CastByUnit",
                    ["size"] = 24,
                    ["yOffset"] = -2,
                },
                ["castbar"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["iconOffsetY"] = -1,
                    ["iconSize"] = 27,
                    ["sourceInterrupt"] = false,
                    ["width"] = 160,
                    ["yOffset"] = -13,
                },
                ["debuffs"] = {
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 14,
                    ["font"] = "GothamNarrowUltra",
                    ["fontSize"] = 12,
                    ["priority"] = "Blacklist,Personal,CastByNPC",
                    ["size"] = 24,
                    ["yOffset"] = -2,
                },
                ["health"] = {
                    ["height"] = 18,
                    ["text"] = {
                        ["font"] = "Mikko",
                        ["fontSize"] = 14,
                        ["format"] = "[perhp]%",
                        ["xOffset"] = 1,
                    },
                },
                ["level"] = {
                    ["enable"] = false,
                    ["font"] = "Mikko",
                    ["fontSize"] = 12,
                    ["format"] = "[difficultycolor][level][shortclassification]",
                    ["xOffset"] = 22,
                    ["yOffset"] = -15,
                },
                ["name"] = {
                    ["font"] = "Mikko",
                    ["fontSize"] = 14,
                    ["format"] = "[name:medium]",
                    ["position"] = "CENTER",
                    ["yOffset"] = 16,
                },
                ["power"] = {
                    ["displayAltPower"] = true,
                },
                ["title"] = {
                    ["format"] = "[npctitle]",
                },
            },
            ["TARGET"] = {
                ["glowStyle"] = "style7",
            },
        },
        ["visibility"] = {
            ["enemy"] = {
                ["guardians"] = true,
                ["totems"] = true,
            },
        },
    },
    ["tooltip"] = {
        ["font"] = "Mikko",
        ["fontOutline"] = "OUTLINE",
        ["headerFont"] = "Mikko",
        ["headerFontOutline"] = "OUTLINE",
        ["healthBar"] = {
            ["font"] = "Mikko",
            ["statusPosition"] = "TOP",
        },
        ["visibility"] = {
            ["combatOverride"] = "HIDE",
        },
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.94,
                ["g"] = 0.8,
                ["r"] = 0.41,
            },
            ["auraBarByType"] = false,
            ["castColor"] = {
                ["b"] = 1,
                ["g"] = 0.63921568627451,
                ["r"] = 0,
            },
            ["castbar_backdrop"] = {
                ["a"] = 0.60000002384186,
                ["b"] = 0.14901960784314,
                ["g"] = 0.14901960784314,
                ["r"] = 0.14901960784314,
            },
            ["classResources"] = {
                ["comboPoints"] = {
                    [1] = {
                        ["b"] = 0,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    [2] = {
                        ["b"] = 0,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    [3] = {
                        ["b"] = 0,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                },
            },
            ["colorhealthbyvalue"] = false,
            ["customcastbarbackdrop"] = true,
            ["customhealthbackdrop"] = true,
            ["custompowerbackdrop"] = true,
            ["frameGlow"] = {
                ["mouseoverGlow"] = {
                    ["enable"] = false,
                },
            },
            ["healPrediction"] = {
                ["absorbs"] = {
                    ["a"] = 0.40000003576279,
                },
                ["overabsorbs"] = {
                    ["a"] = 0.40000003576279,
                },
            },
            ["health"] = {
                ["b"] = 0.070588235294118,
                ["g"] = 0.070588235294118,
                ["r"] = 0.062745098039216,
            },
            ["health_backdrop"] = {
                ["b"] = 0.070588235294118,
                ["g"] = 0.070588235294118,
                ["r"] = 0.070588235294118,
            },
            ["healthclass"] = true,
            ["power"] = {
                ["ALT_POWER"] = {
                    ["b"] = 1,
                    ["g"] = 0.63921568627451,
                    ["r"] = 0,
                },
                ["INSANITY"] = {
                    ["b"] = 0.69019607843137,
                    ["g"] = 0.14117647058823,
                    ["r"] = 0.54901960784314,
                },
                ["MAELSTROM"] = {
                    ["g"] = 0.63921568627451,
                },
                ["MANA"] = {
                    ["b"] = 1,
                    ["g"] = 0.63921568627451,
                    ["r"] = 0,
                },
            },
            ["power_backdrop"] = {
                ["b"] = 0.10196078431373,
                ["g"] = 0.10196078431373,
                ["r"] = 0.10196078431373,
            },
            ["tapped"] = {
                ["b"] = 0.61176470588235,
                ["g"] = 0.56862745098039,
                ["r"] = 0.54901960784314,
            },
        },
        ["cooldown"] = {
            ["fonts"] = {
                ["enable"] = true,
                ["font"] = "Mikko",
            },
            ["threshold"] = -1,
        },
        ["font"] = "Mikko",
        ["fontOutline"] = "OUTLINE",
        ["fontSize"] = 14,
        ["smartRaidFilter"] = false,
        ["smoothbars"] = true,
        ["statusbar"] = "Melli",
        ["targetOnMouseDown"] = true,
        ["units"] = {
            ["arena"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["maxDuration"] = 0,
                    ["sizeOverride"] = 20,
                    ["xOffset"] = 2,
                    ["yOffset"] = -10,
                },
                ["castbar"] = {
                    ["height"] = 12,
                    ["width"] = 180,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["maxDuration"] = 0,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 36,
                    ["xOffset"] = 1,
                    ["yOffset"] = 0,
                },
                ["disableMouseoverGlow"] = true,
                ["disableTargetGlow"] = true,
                ["enable"] = false,
                ["growthDirection"] = "UP",
                ["health"] = {
                    ["text_format"] = "[health:current] || [perhp]%",
                    ["xOffset"] = -2,
                },
                ["height"] = 36,
                ["infoPanel"] = {
                    ["height"] = 16,
                },
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:veryshort]",
                    ["yOffset"] = 16,
                },
                ["portrait"] = {
                    ["camDistanceScale"] = 1,
                    ["width"] = 35,
                },
                ["power"] = {
                    ["height"] = 4,
                    ["text_format"] = "",
                    ["xOffset"] = 2,
                },
                ["spacing"] = 17,
                ["width"] = 180,
            },
            ["assist"] = {
                ["enable"] = false,
            },
            ["boss"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["countFont"] = "Mikko",
                    ["countPosition"] = "BOTTOM",
                    ["countXOffset"] = 2,
                    ["countYOffset"] = -4,
                    ["priority"] = "Boss,Blacklist",
                    ["sizeOverride"] = 20,
                    ["xOffset"] = 2,
                    ["yOffset"] = -15,
                },
                ["castbar"] = {
                    ["height"] = 12,
                    ["width"] = 160,
                },
                ["customTexts"] = {
                    ["Power text"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Mikko",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[powercolor][power:percent]",
                        ["xOffset"] = 1,
                        ["yOffset"] = -14,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["countFont"] = "Mikko",
                    ["countPosition"] = "BOTTOM",
                    ["countYOffset"] = -4,
                    ["perrow"] = 2,
                    ["sizeOverride"] = 28,
                    ["xOffset"] = 1,
                    ["yOffset"] = -1,
                },
                ["disableMouseoverGlow"] = true,
                ["disableTargetGlow"] = true,
                ["growthDirection"] = "UP",
                ["health"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "[health:current:shortvalue] || [perhp]%",
                    ["yOffset"] = -8,
                },
                ["height"] = 28,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:veryshort:translit]",
                    ["yOffset"] = 8,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 4,
                    ["position"] = "LEFT",
                    ["text_format"] = "[powercolor][power:percent]",
                    ["xOffset"] = 2,
                },
                ["spacing"] = 17,
                ["width"] = 160,
            },
            ["focus"] = {
                ["castbar"] = {
                    ["enable"] = false,
                    ["height"] = 28,
                    ["width"] = 340,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["enable"] = false,
                },
                ["disableTargetGlow"] = true,
                ["height"] = 16,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:veryshort:translit]",
                    ["yOffset"] = 15,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 5,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
                ["threatStyle"] = "NONE",
                ["width"] = 100,
            },
            ["party"] = {
                ["ROLE1"] = "HEALER",
                ["ROLE2"] = "TANK",
                ["buffIndicator"] = {
                    ["size"] = 10,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "Mikko",
                    ["countPosition"] = "BOTTOM",
                    ["countYOffset"] = -4,
                    ["enable"] = true,
                    ["growthX"] = "LEFT",
                    ["perrow"] = 2,
                    ["sizeOverride"] = 20,
                    ["xOffset"] = -2,
                    ["yOffset"] = -15,
                },
                ["classbar"] = {
                    ["enable"] = false,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "LEFT",
                    ["clickThrough"] = true,
                    ["countFont"] = "Mikko",
                    ["countPosition"] = "BOTTOM",
                    ["countYOffset"] = -4,
                    ["perrow"] = 2,
                    ["priority"] = "Blacklist,Personal,nonPersonal",
                    ["sizeOverride"] = 28,
                    ["xOffset"] = -1,
                    ["yOffset"] = -1,
                },
                ["disableMouseoverGlow"] = true,
                ["disableTargetGlow"] = true,
                ["groupBy"] = "ROLE",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "BOTTOM",
                    ["text_format"] = "",
                    ["xOffset"] = 0,
                    ["yOffset"] = 4,
                },
                ["height"] = 28,
                ["horizontalSpacing"] = 1,
                ["infoPanel"] = {
                    ["height"] = 12,
                },
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "[name:veryshort:translit]",
                    ["yOffset"] = 8,
                },
                ["orientation"] = "MIDDLE",
                ["petsGroup"] = {
                    ["xOffset"] = 0,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 3,
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "",
                    ["yOffset"] = 2,
                },
                ["raidRoleIcons"] = {
                    ["position"] = "TOPRIGHT",
                },
                ["raidicon"] = {
                    ["attachTo"] = "RIGHT",
                    ["size"] = 12,
                    ["xOffset"] = -3,
                    ["yOffset"] = -10,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "vixar",
                    ["fontOutline"] = "OUTLINE",
                    ["size"] = 18,
                    ["stack"] = {
                        ["position"] = "RIGHT",
                        ["xOffset"] = 4,
                        ["yOffset"] = -5,
                    },
                    ["xOffset"] = 28,
                    ["yOffset"] = 12,
                },
                ["readycheckIcon"] = {
                    ["size"] = 14,
                    ["yOffset"] = 4,
                },
                ["roleIcon"] = {
                    ["enable"] = false,
                    ["xOffset"] = 1,
                    ["yOffset"] = -1,
                },
                ["showPlayer"] = false,
                ["threatStyle"] = "NONE",
                ["verticalSpacing"] = 10,
                ["width"] = 160,
            },
            ["pet"] = {
                ["buffs"] = {
                    ["priority"] = "CastByNPC",
                    ["sizeOverride"] = 46,
                },
                ["castbar"] = {
                    ["enable"] = false,
                    ["height"] = 24,
                    ["iconSize"] = 32,
                    ["width"] = 340,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "LEFT",
                    ["perrow"] = 1,
                    ["priority"] = "Blacklist,Personal",
                    ["sizeOverride"] = 36,
                    ["xOffset"] = -1,
                    ["yOffset"] = 10,
                },
                ["height"] = 12,
                ["infoPanel"] = {
                    ["height"] = 14,
                },
                ["name"] = {
                    ["text_format"] = "[name:short:translit]",
                    ["xOffset"] = 2,
                    ["yOffset"] = -4,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 5,
                },
                ["threatStyle"] = "NONE",
                ["width"] = 100,
            },
            ["player"] = {
                ["RestIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["castbar"] = {
                    ["enable"] = false,
                    ["height"] = 24,
                    ["icon"] = false,
                    ["iconAttached"] = false,
                    ["width"] = 276,
                },
                ["classbar"] = {
                    ["detachFromFrame"] = true,
                    ["enable"] = false,
                    ["height"] = 15,
                },
                ["customTexts"] = {
                    ["Absorb"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Mikko",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[absorbs]",
                        ["xOffset"] = -1,
                        ["yOffset"] = -1,
                    },
                },
                ["debuffs"] = {
                    ["enable"] = false,
                    ["perrow"] = 6,
                    ["yOffset"] = 3,
                },
                ["health"] = {
                    ["position"] = "BOTTOMRIGHT",
                    ["text_format"] = "[perhp]% || [health:current:shortvalue]",
                    ["xOffset"] = 0,
                    ["yOffset"] = -17,
                },
                ["height"] = 26,
                ["name"] = {
                    ["position"] = "TOPLEFT",
                    ["text_format"] = "[name:veryshort:translit]",
                    ["xOffset"] = 2,
                    ["yOffset"] = 8,
                },
                ["portrait"] = {
                    ["overlay"] = true,
                },
                ["power"] = {
                    ["detachFromFrame"] = true,
                    ["enable"] = false,
                    ["height"] = 12,
                    ["hideonnpc"] = true,
                    ["text_format"] = "",
                },
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["enable"] = false,
                    ["yOffset"] = 2,
                },
                ["threatStyle"] = "NONE",
                ["width"] = 220,
            },
            ["raid"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                },
                ["classbar"] = {
                    ["enable"] = false,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["clickThrough"] = true,
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 11,
                    ["countPosition"] = "BOTTOM",
                    ["countXOffset"] = 1,
                    ["countYOffset"] = -4,
                    ["enable"] = true,
                    ["priority"] = "Blacklist,Personal,nonPersonal",
                    ["sizeOverride"] = 20,
                    ["xOffset"] = 1,
                    ["yOffset"] = -22,
                },
                ["disableTargetGlow"] = true,
                ["groupBy"] = "ROLE",
                ["growthDirection"] = "UP_LEFT",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["text_format"] = "",
                    ["yOffset"] = 4,
                },
                ["height"] = 46,
                ["horizontalSpacing"] = -1,
                ["name"] = {
                    ["text_format"] = "[name:veryshort:translit]",
                },
                ["numGroups"] = 4,
                ["power"] = {
                    ["enable"] = false,
                },
                ["raidicon"] = {
                    ["attachTo"] = "TOPRIGHT",
                    ["enable"] = false,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "vixar",
                    ["fontOutline"] = "OUTLINE",
                    ["size"] = 17,
                    ["stack"] = {
                        ["position"] = "RIGHT",
                        ["xOffset"] = 4,
                        ["yOffset"] = -5,
                    },
                    ["xOffset"] = 69,
                    ["yOffset"] = 2,
                },
                ["roleIcon"] = {
                    ["enable"] = false,
                },
                ["threatStyle"] = "NONE",
                ["verticalSpacing"] = -1,
                ["width"] = 90,
            },
            ["raid40"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                },
                ["classbar"] = {
                    ["enable"] = false,
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["clickThrough"] = true,
                    ["countFont"] = "Mikko",
                    ["countFontSize"] = 10,
                    ["countPosition"] = "BOTTOM",
                    ["countYOffset"] = -4,
                    ["enable"] = true,
                    ["priority"] = "Blacklist,Personal,nonPersonal",
                    ["sizeOverride"] = 16,
                    ["xOffset"] = 1,
                    ["yOffset"] = -18,
                },
                ["disableTargetGlow"] = true,
                ["growthDirection"] = "LEFT_UP",
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["text_format"] = "",
                    ["yOffset"] = 4,
                },
                ["height"] = 46,
                ["horizontalSpacing"] = -1,
                ["name"] = {
                    ["text_format"] = "[name:veryshort:translit]",
                },
                ["raidicon"] = {
                    ["attachTo"] = "TOPRIGHT",
                    ["enable"] = false,
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["font"] = "vixar",
                    ["fontOutline"] = "OUTLINE",
                    ["size"] = 17,
                    ["stack"] = {
                        ["position"] = "RIGHT",
                        ["xOffset"] = 4,
                        ["yOffset"] = -5,
                    },
                    ["xOffset"] = 69,
                    ["yOffset"] = 2,
                },
                ["roleIcon"] = {
                    ["xOffset"] = 1,
                    ["yOffset"] = -1,
                },
                ["threatStyle"] = "NONE",
                ["verticalSpacing"] = -1,
                ["width"] = 90,
            },
            ["tank"] = {
                ["enable"] = false,
            },
            ["target"] = {
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["countFont"] = "Mikko",
                    ["countPosition"] = "TOP",
                    ["countYOffset"] = 6,
                    ["numrows"] = 2,
                    ["perrow"] = 5,
                    ["priority"] = "Blacklist,Personal,Boss,nonPersonal",
                    ["sizeOverride"] = 25,
                    ["yOffset"] = 18,
                },
                ["castbar"] = {
                    ["enable"] = false,
                    ["height"] = 20,
                    ["width"] = 220,
                },
                ["customTexts"] = {
                    ["Power text"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Mikko",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 14,
                        ["text_format"] = "[powercolor][power:percent]",
                        ["xOffset"] = 2,
                        ["yOffset"] = -22,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "Mikko",
                    ["countPosition"] = "TOP",
                    ["countYOffset"] = 6,
                    ["growthX"] = "RIGHT",
                    ["perrow"] = 4,
                    ["priority"] = "Blacklist,Personal,CastByNPC",
                    ["sizeOverride"] = 24,
                    ["yOffset"] = 1,
                },
                ["health"] = {
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "[health:current:shortvalue] || [perhp]%",
                    ["xOffset"] = 2,
                    ["yOffset"] = -17,
                },
                ["height"] = 26,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:short:translit]",
                    ["yOffset"] = 8,
                },
                ["portrait"] = {
                    ["overlay"] = true,
                },
                ["power"] = {
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 72,
                    ["height"] = 4,
                    ["offset"] = 3,
                    ["position"] = "BOTTOMLEFT",
                    ["text_format"] = "",
                    ["width"] = "spaced",
                    ["xOffset"] = -7,
                },
                ["raidicon"] = {
                    ["attachTo"] = "CENTER",
                    ["enable"] = false,
                    ["yOffset"] = 2,
                },
                ["threatStyle"] = "NONE",
                ["width"] = 220,
            },
            ["targettarget"] = {
                ["debuffs"] = {
                    ["enable"] = false,
                },
                ["height"] = 16,
                ["name"] = {
                    ["position"] = "TOPRIGHT",
                    ["text_format"] = "[name:veryshort:translit]",
                    ["yOffset"] = 15,
                },
                ["power"] = {
                    ["enable"] = false,
                    ["height"] = 5,
                },
                ["raidicon"] = {
                    ["enable"] = false,
                },
                ["width"] = 100,
            },
        },
    },
}::profile::Mikko DPS/Tank
